### ISSUE TITLE
Current version 25.0.0 in readme does not exist in maven central

### ISSUE THREAD

**Issue by Janmm14** [JetBrains/java-annotations#106]
Publish it?!

**Comment by amaembo** [comment]
The version is not ready yet. We will publish it when it will be ready

**Comment by Vampire** [comment]
But then the readme should not already contain the next version, should it?
In the past the readme of this project was only updated with the new version right before / with the release.
This also makes sense, because the readme is the first place to go, you copy the instruction and it fails.
This is a bad user experience and I also fell into that trap right now as 25.0.0 is still not released.

To be clear, I'm **not** asking "please finally release 25.0.0", do that whenever it is ready.

But I think the version change in the readme should be reverted and only be done on release like it used to be @amaembo.

**Comment by Janmm14** [comment]
@amaembo

**Comment by Shadow-Devil** [comment]
This is still not fixed, could someone please take a look?

**Comment by amaembo** [comment]
Version 25.0.0 is published.
