### ISSUE TITLE
@Contract on records

### ISSUE THREAD

**Issue by haavar** [JetBrains/java-annotations#68]
Add the target RECORD_COMPONENT to the Contract annotation to allow annotations on records.

**Comment by amaembo** [comment]
What kind of semantics are you trying to express with RECORD_COMPONENT target on Contract? Please show a complete code example.

**Comment by amaembo** [comment]
In this case, `RECORD_COMPONENT` target won't help you, as it's applicable to an individual component (`email` or `phone`), rather than the record itself. To annotate the record, you need a `TYPE` target, but it's too wide and will allow putting annotations on every possible type, not just record. This might be confusing.

Compact constructors exist for this purpose. You can simply write:

```java
public record User(String email, String phone){
    @Contract("null, null -> fail")
    public User {}
}
```

IntelliJ IDEA understands this already and will warn you if you construct an object via `new User(null, null)`.
Compact constructor is desired in your case anyway, because you may need to enforce the invariant at runtime, e.g.:

```java
public record User(String email, String phone){
    @Contract("null, null -> fail")
    public User {
        if (email == null && phone == null) {
            throw new IllegalArgumentException();
        }
    }
}
```
